@host = https://localhost:7283

### Get first page of products
GET {{host}}/api/products
Accept: application/json

### Filter, search, sort and page products
GET {{host}}/api/products?brandId=2&typeId=3&search=jacket&sort=pricedesc&pageIndex=1&pageSize=6
Accept: application/json

### Get product by id
GET {{host}}/api/products/1
Accept: application/json

### Get brands
GET {{host}}/api/products/brands

### Get types
GET {{host}}/api/products/types
